# Generated by Django 4.2.17 on 2024-12-16 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywesbite', '0003_alter_programmingskill_icon_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmingskill',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='icons/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
